# -*- coding: utf-8 -*-
"""test_detection_tracking.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MNY5LzQthJzshIynuzWVN0M8w7eksiXl

# Method 1 (Baseline 기반)

# Method 2 (완전 밑바닥부터 - YOLOv11 기반)
"""

from google.colab import drive
drive.mount('/content/drive')

import os

drive_path = "/content/drive/MyDrive/Colab Notebooks/CVIP 랩/UAV/Track 1"
local_data_path = '/content/data'
train_dir = "train"  # 압축 풀렸을 때 생성되는 폴더명 (확인 필요)
test_dir = "track1_test" # 압축 풀렸을 때 생성되는 폴더명 (확인 필요)

# 1. 가장 빠른 .tar 파일이 이미 만들어져 있는지 확인
if os.path.exists(f"{drive_path}/train.tar") and os.path.exists(f"{drive_path}/track1_test.tar"):
    print("🚀 고속 로딩용 tar 파일 발견! 로딩 시작.")

    !mkdir -p {local_data_path}

    # tar 파일 복사 (용량이 커도 단일 파일이라 빠름)
    !cp "{drive_path}/train.tar" /content/
    !cp "{drive_path}/track1_test.tar" /content/

    print("📦 tar 압축 해제 중 (zip보다 훨씬 빠릅니다)...")
    !tar -xf /content/train.tar -C {local_data_path}
    !tar -xf /content/track1_test.tar -C {local_data_path}

    print("✅ 데이터 준비 완료!")

# 2. tar는 없고 원본 .zip만 있는 경우 (최초 1회 실행됨)
elif os.path.exists(f"{drive_path}/train.zip") and os.path.exists(f"{drive_path}/track1_test.zip"):
    print("🐢 zip 파일만 발견되었습니다. (최초 1회 변환 작업 시작)")
    print("💡 팁: 이 작업은 한 번만 수행하면 됩니다. 다음 실행부터는 자동으로 tar를 사용하여 빨라집니다.")

    !mkdir -p {local_data_path}

    # zip 복사
    !cp "{drive_path}/train.zip" /content/
    !cp "{drive_path}/track1_test.zip" /content/

    print("📂 zip 압축 해제 중 (시간이 좀 걸립니다)...")
    !unzip -q /content/train.zip -d {local_data_path}
    !unzip -q /content/track1_test.zip -d {local_data_path}

    print("⚡ 로딩 속도 향상을 위해 tar로 변환 및 백업 중...")

    # 로컬에 풀린 폴더를 tar로 묶음 (경로 주의: data 폴더 안의 내용물을 묶음)
    # 아래 명령어는 /content/data/train 폴더를 train.tar로 묶는다는 의미
    !tar -cf /content/train.tar -C {local_data_path} {train_dir}
    !tar -cf /content/track1_test.tar -C {local_data_path} {test_dir}

    # 만들어진 tar 파일을 드라이브로 이동 (백업)
    print("💾 변환된 tar 파일을 구글 드라이브로 업로드 중...")
    !mv /content/train.tar "{drive_path}/"
    !mv /content/track1_test.tar "{drive_path}/"

    print("✅ 변환 및 데이터 준비 완료! 이제 드라이브를 확인해보시면 tar 파일이 생성되어 있을 겁니다.")

# 3. 아무 파일도 없는 경우
else:
    print(f"❌ 오류: {drive_path} 경로에서 zip 또는 tar 파일을 찾을 수 없습니다.")
    if os.path.exists(drive_path):
        print("현재 폴더 파일 목록:", os.listdir(drive_path))

!ls /content/data

!ls -lh

# train 폴더 안에 파일들이 잘 들어있는지 확인하는 명령어
!ls /content/data/train | head

from __future__ import absolute_import
import numpy as np
import cv2
from tqdm import tqdm
import json
import glob
import os

from detection_siamfc import TrackerSiamFC # Drive Check 하기

def iou(bbox1, bbox2):
    # bbox는 형식이 (x, y, w, h)이니까, corner format으로 변환
    bbox1 = [float(x) for x in bbox1]
    bbox2 = [float(x) for x in bbox2]

    (x0_1, y0_1, w1_1, h1_1) = bbox1
    (x0_2, y0_2, w1_2, h1_2) = bbox2
    x1_1 = x0_1 + w1_1
    x1_2 = x0_2 + w1_2
    y1_1 = y0_1 + h1_1
    y1_2 = y0_2 + h1_2

    overlap_x0 = max(x0_1, x0_2)
    overlap_y0 = max(y0_1, y0_2)
    overlap_x1 = min(x1_1, x1_2)
    overlap_y1 = min(y1_1, y1_2)

    if overlap_x1 - overlap_x0 <= 0 or overlap_y1 - overlap_y0 <=0:
        return 0

    size_1 = (x1_1 - x0_1) * (y1_1, y0_1)
    size_2 = (x1_2 - x0_2) * (y1_2, y0_2)

    size_intersection = (overlap_x1 - overlap_x0) * (overlap_y1 - overlap_y0)
    size_union = size_1 + size_2 - size_intersection

    return size_intersection / size_union

def not_exist(pred):
    return (len(pred) == 1 and pred[0] == 0) or (len(pred) == 0)

def eval(out_res, label_res):
    measure_per_frame = []
    penalty_measure = []
    for _pred, _gt, _exist in zip(out_res, label_res['gt_rect'], label_res['exist']):
        # Target 존재 x : _exist==False | Target 존재 O : _exist == True
        measure_per_frame.append(not_exist(_pred) if not _exist else iou(_pred, _gt) if len(_pred) > 1 else 0)
        if _exist:
            if (len(_pred) > 1 and iou(_pred, _gt) > 1e-5):
                penalty_measure.append(0)
            else:
                penalty_measure.append(1)
    if len(measure_per_frame) == 0:
        measure_per_frame_mean = 0
    else:
        measure_per_frame_mean = np.mean(measure_per_frame)

    if len(penalty_measure) == 0:
        penalty_measure_mean = 0
    else:
        penalty_measure_mean = np.mean(penalty_measure)

    return measure_per_frame_mean - 0.2 * (penalty_measure_mean ** 0.3)

def main(mode='IR', visualization=False):
    assert mode in ['IR', 'RGB'], 'Only Support IR or RGB to evaluate'

    net_path = 'model.pth'
    tracker = TrackerSiamFC(net_path=net_path)
    yolo_model = tracker.initialize_yolo()
    video_paths = glob.glob(os.path.join(r'D:\DataSet\UAV\track2_test', '*'))
    video_num = len(video_paths)
    output_dir = os.path.join('results', tracker.name)
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)
    overall_performance = []

    # run tracking experiments and report performance
    for video_id, video_path in enumerate(video_paths, start=1):
        video_name = os.path.basename(video_path) # 파일 경로에서 마지막 구성 요소만 추출 \\ 제일 마지막꺼
        video_file = os.path.join(video_path, '%s.mp4'%mode)
        frame_files = sorted(
            [f for f in os.listdir(video_path) if f.endswith(('.jpg', '.jpeg', '.png', '.bmp'))])  # 得到视频帧路径list

        res_file = os.path.join(r"D:\DataSet\Label\track2_test_labels",video_name, '%s_label.json'%mode)
        with open(res_file, 'r') as f:
            label_res = json.load(f)

        output_file = os.path.join(output_dir, '%s.txt' % video_name)
        # capture = cv2.VideoCapture(video_file)
        if os.path.exists(output_file): #存在
            # print("-1", output_file)
            with open(output_file, 'r') as file:
                # 读取文件内容
                content = file.read()
                # 将内容解析为JSON对象
                data = json.loads(content)
                # 提取res字段
                out_res = data['res']
        else:
            frame_id = 0
            out_res = []
            pred_bbox = [0] # no prection

            for frame_file in frame_files:
                frame_path = os.path.join(video_path, frame_file)
                frame = cv2.imread(frame_path)

                im_vis = frame.copy()
                if len(pred_bbox) == 1:
                    pred_bbox, im_vis = tracker.init(frame, yolo_model)  # initialization
                    out_res.append(pred_bbox)

                    cv2.putText(im_vis, str(frame_id), (40, 40), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 255), 2)
                    if len(pred_bbox) == 1:
                        cv2.putText(im_vis, 'Fail to detect the UAV', (100, 40), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 0, 255),
                                    2)
                    else:
                        pred_bbox = list(map(int, pred_bbox))
                        cv2.rectangle(im_vis, (pred_bbox[0], pred_bbox[1]),
                                      (pred_bbox[0] + pred_bbox[2], pred_bbox[1] + pred_bbox[3]), (0, 0, 255), 3)
                else:
                    pred_bbox = tracker.update(frame)  # tracking
                    pred_bbox = list(map(int, pred_bbox))
                    out_res.append(pred_bbox)
                    cv2.rectangle(im_vis, (pred_bbox[0], pred_bbox[1]),
                                  (pred_bbox[0] + pred_bbox[2], pred_bbox[1] + pred_bbox[3]), (0, 0, 255), 3)
                    cv2.putText(im_vis, str(frame_id), (40, 40), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 255), 2)

                if visulization:
                    cv2.imshow(video_name, im_vis)
                    cv2.waitKey(1)

                frame_id += 1
            if visulization:
                cv2.destroyAllWindows()
            # save result
            output_file = os.path.join(output_dir, '%s.txt' % video_name)
            with open(output_file, 'w') as f:
                json.dump({'res': out_res}, f)

        mixed_measure = eval(out_res, label_res)
        overall_performance.append(mixed_measure)
        print('[%03d/%03d] %20s %5s Fixed Measure: %.03f' % (video_id, video_num, video_name, mode, mixed_measure))

    print('[Overall] %5s Mixed Measure: %.03f\n' % (mode, np.mean(overall_performance)))


if __name__ == '__main__':
    main(mode='IR', visulization=False)