# -*- coding: utf-8 -*-
"""Residual 시각화.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18Py1zW-kZm8By4RMlfGx-Y7RdcycaTeZ
"""

# Commented out IPython magic to ensure Python compatibility.
# %cd /content
!git clone https://github.com/ultralytics/yolov5
# %cd yolov5
!pip install -r requirements.txt

from google.colab import drive
drive.mount('/content/drive')

import sys
sys.path.append('/content/yolov5')
sys.path.append('/content/drive/MyDrive/Colab Notebooks/CVIP_LAB/UAV/Track 1')

# 구글 드라이브의 zip 파일을 직접 /content/data 폴더에 조용히(-q) 압축 해제
# Train은 추론에 필요 없으니까 해제할 필요 X
!unzip -q "/content/drive/MyDrive/Colab Notebooks/CVIP_LAB/UAV/Track 1/tar_file/train.zip" -d /content/data
!unzip -q "/content/drive/MyDrive/Colab Notebooks/CVIP_LAB/UAV/Track 1/tar_file/track1_test.zip" -d /content/data

!rm -rf /content/data/__MACOSX

!ls /content/yolov5/Datasets/train | head

import json
with open("/content/data/train/01_1751_0250-1750/IR_label.json") as f:
    data = json.load(f)
print(type(data))
print(data.keys() if isinstance(data, dict) else data[:1])

data['gt_rect'][:5]

import os
drive_path = '/content/drive/MyDrive/Colab Notebooks/CVIP_LAB/UAV/Track 1'
track1_test_path = '/content/data/track1_test'

print(f"Checking directory : {track1_test_path}")

if os.path.exists(track1_test_path):
    print("Directory Exists. Listing Contents.")
    contents = os.listdir(track1_test_path)
    if contents:
        for content in contents[:10]:
            print(f"- {content}")
        if len(contents) > 10:
            print(f"... and {len(contents) - 10} more items")
        else:
            print("Directory is empty")
else:
    print("Directory does not exist.")

# Link to Yolov5
!ln -s /content/data /content/yolov5/Datasets
!ls /content/yolov5/Datasets/train | head

from __future__ import absolute_import
import numpy as np
import cv2
from tqdm import tqdm
import json
import glob
import os

from detection_siamfc import TrackerSiamFC

def iou(bbox1, bbox2):
    bbox1 = [float(x) for x in bbox1]
    bbox2 = [float(x) for x in bbox2]

    (x0_1, y0_1, w1_1, h1_1) = bbox1
    (x0_2, y0_2, w1_2, h1_2) = bbox2
    x1_1 = x0_1 + w1_1
    x1_2 = x0_2 + w1_2
    y1_1 = y0_1 + h1_1
    y1_2 = y0_2 + h1_2

    overlap_x0 = max(x0_1, x0_2)
    overlap_y0 = max(y0_1, y0_2)
    overlap_x1 = min(x1_1, x1_2)
    overlap_y1 = min(y1_1, y1_2)

    if overlap_x1 - overlap_x0 <= 0 or overlap_y1 - overlap_y0 <=0:
        return 0

    size_1 = (x1_1 - x0_1) * (y1_1 - y0_1)
    size_2 = (x1_2 - x0_2) * (y1_2 - y0_2)

    size_intersection = (overlap_x1 - overlap_x0) * (overlap_y1 - overlap_y0)
    size_union = size_1 + size_2 - size_intersection

    return size_intersection / size_union

def not_exist(pred):
    return (len(pred) == 1 and pred[0] == 0) or (len(pred) == 0)

def eval_aoa(out_res, label_res):
    measure_per_frame = []
    penalty_measure = []
    for _pred, _gt, _exist in zip(out_res, label_res['gt_rect'], label_res['exist']):
        # Target 존재 x : _exist==False | Target 존재 O : _exist == True
        measure_per_frame.append(not_exist(_pred) if not _exist else iou(_pred, _gt) if len(_pred) > 1 else 0)
        if _exist:
            if (len(_pred) > 1 and iou(_pred, _gt) > 1e-5):
                penalty_measure.append(0)
            else:
                penalty_measure.append(1)
    if len(measure_per_frame) == 0:
        measure_per_frame_mean = 0
    else:
        measure_per_frame_mean = np.mean(measure_per_frame)

    if len(penalty_measure) == 0:
        penalty_measure_mean = 0
    else:
        penalty_measure_mean = np.mean(penalty_measure)

    return measure_per_frame_mean - 0.2 * (penalty_measure_mean ** 0.3)

import os
import cv2
import json
import glob
import torch
import numpy as np
import zipfile
from google.colab.patches import cv2_imshow
from IPython.display import clear_output

import logging
from yolov5.utils.general import LOGGER
LOGGER.setLevel(logging.WARNING)

def main(mode='IR', visualization=False, target_folders=None):
    # Lucas-Kanade Optical Flow Parameter settings.
    # == Lucas-Kanade operate flow ==
    # p0 (prev frame)  -> calcOpticalFlowPyrLK -> p1(current frame position)
    # p0 : feature coordinate on prev_frame  |   p1 : position of the feature at current frame
    # and estimae camera motion matrix by using ` M = estimateAffinePartial2D(good_old, good_new)`
    lk_params = dict(
        winSize=(15, 15),
        maxLevel=2,
        criteria=(cv2.TERM_CRITERIA_EPS | cv2.TERM_CRITERIA_COUNT, 10, 0.03)
    )
    global drive_path
    device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
    print(f"현재 사용 장치 : {device}")

    net_path = os.path.join(drive_path, "Baseline_code", 'model.pth')
    tracker = TrackerSiamFC(net_path=net_path)
    yolo_model = tracker.initialize_yolo()
    yolo_model.to(device)
    tracker.net.to(device)

    submission_dir = os.path.join("results", "submission_files")
    os.makedirs(submission_dir, exist_ok=True)

    base_dir = '/content/data/track1_test'


    if target_folders is None:
        video_paths = sorted([os.path.join(base_dir, d) for d in os.listdir(base_dir) if os.path.isdir(os.path.join(base_dir, d))])
    else:
        video_paths = sorted([os.path.join(base_dir, d) for d in target_folders if os.path.isdir(os.path.join(base_dir, d))])

    output_dir = os.path.join('results', tracker.name)
    os.makedirs(output_dir, exist_ok=True)

    local_output_dir = '/content/data'
    overall_success = []

    print(f"Total Video nums : {len(video_paths)}")

    for video_id, video_path in enumerate(video_paths, start=1):
        print(f"\n===== {video_id}/{len(video_paths)} =====")
        saved_debug = False

        gmc_initialized = False
        track_active = False
        prev_gray = None
        p0 = None
        video_preds = [] # for evaluate (float : for precision)
        out_res = [] # for CodaLab Submission (int : for preventing format_error)
        video_name = os.path.basename(video_path)
        frame_files = sorted([
            f for f in os.listdir(video_path)
            if f.endswith(('.jpg', '.png', '.jpeg'))
        ])
        res_file = os.path.join(video_path, 'IR_label.json')
        with open(res_file, 'r') as f:
            label_res = json.load(f)

        if 'exist' not in label_res:
            label_res['exist'] = [1] * len(label_res['gt_rect'])

        gt_rects = label_res['gt_rect']
        exist_flags = label_res['exist']
        video_ious = []

        # Calculate num_frames to prevent IndexError
        if len(gt_rects) > 1: # 꼭!!
            num_frames = min(len(frame_files), len(gt_rects))
        else:
            num_frames = len(frame_files)

        ########
        if visualization and len(frame_files) > 0:
            first_frame_path = os.path.join(video_path, frame_files[0])
            first_frame = cv2.imread(first_frame_path)
            h, w = first_frame.shape[:2]

            out_video_path = os.path.join(local_output_dir, f"{video_name}_tracked.mp4")
            fourcc = cv2.VideoWriter_fourcc(*'mp4v')
            video_writer = cv2.VideoWriter(out_video_path, fourcc, 30.0, (w, h))
        ########

        for frame_id in range(num_frames):
            frame_file = frame_files[frame_id]
            frame_path = os.path.join(video_path, frame_file)
            frame = cv2.imread(frame_path)
            curr_gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
            im_vis = frame.copy()

            if not track_active: # Tracking 할 것 없음
                # ================ original ================
                # label.json (gt_rects[0] : 초기 좌표)를 무시하고 YOLO가 첫 프레임부터 스스로 찾아야 함
                # pred_bbox, im_vis = tracker.init(frame, yolo_model)
                # if len(pred_bbox) > 1:
                #     track_active = True
                #     gmc_initialized = False
                # else:
                #     pred_bbox = [0]
                # ==========================================

                # ================ fixed version ================
                # 첫 프레임이면 무조건 GT로 SiamFC 초기화 하기
                if frame_id == 0 and len(gt_rects) > 0 and exist_flags[0] == 1:
                    init_box = list(gt_rects[0])
                    min_size=30
                    pad_w = max(0, min_size-init_box[2])
                    pad_h = max(0, min_size-init_box[3])
                    init_box[0] -=pad_w / 2
                    init_box[1] -= pad_h /2
                    init_box[2] += pad_w
                    init_box[3] += pad_h

                    pred_bbox, im_vis = tracker.init_with_bbox(frame, init_box)
                    track_active=True
                    gmc_initialized=False

                    # pred_bbox, im_vis = tracker.init_with_bbox(frame, gt_rects[0])
                    # track_active=True
                    # gmc_initialized=False

                else:
                    pred_bbox, im_vis = tracker.init(frame, yolo_model)
                    if len(pred_bbox) > 1:
                        track_active = True
                        gmc_initialized=False
                    else:
                        pred_bbox = [0]
                # ===============================================

            else:
                pred_bbox = tracker.update(frame)

                if len(pred_bbox) == 1:
                    track_active = False
                    gmc_initialized = False
                    pred_bbox = [0]

            if track_active and not gmc_initialized:
                prev_gray = curr_gray.copy()
                p0 = cv2.goodFeaturesToTrack(prev_gray, 80, 0.01, 7, blockSize=7)
                gmc_initialized = True

            elif track_active and gmc_initialized:

                if p0 is not None and len(p0) > 15:
                  # p1 : p0에 있던 점들이 현재 프레임에서 이사 간 새로운 좌표들.
                    p1, st, err = cv2.calcOpticalFlowPyrLK(
                        prev_gray, curr_gray, p0, None, **lk_params)
                    good_new = p1[st == 1]
                    good_old = p0[st == 1]
                    if len(good_old) > 15: # 기존에 존재하던 좌표들 중 몇개가 살아남았는가
                        M, _ = cv2.estimateAffinePartial2D(
                            good_old, good_new,
                            method=cv2.RANSAC,
                            ransacReprojThreshold=3)
                        # M (Affine Model): 2x3 Affine 변환 행렬
                        # _ (linear_mask) : RANSAC이 특징점들 중 카메라 움직임 모델M을 계산하는데 기여한 정상적인 점과 이상치를 구분한 결과값 (1차원 배열 : 1 | 0)

                        if M is not None: # 주어진 대응점들로 유효한 Affine 모델을 추정할 수 있을 때

                            h_img, w_img = curr_gray.shape
                            warped_prev = cv2.warpAffine(prev_gray, M, (w_img, h_img))

                            # 원본 잔차 (이진화 전)
                            residual_raw = cv2.absdiff(warped_prev, curr_gray)

                            ## 이진화 과정 (삭제 후보) : 차분 영상에서 노이즈 제거, 확실한 움직임만 남기기 [배경 노이즈는 0으로 날아가고]
                            _, residual_thresh = cv2.threshold(residual_raw, 20, 255, cv2.THRESH_BINARY)

                            residual = residual_thresh

                            if not saved_debug:
                                debug_dir = '/content/debug_residual'
                                os.makedirs(debug_dir, exist_ok=True)

                                combined_debug = cv2.hconcat([curr_gray, residual_raw, residual])
                                debug_path = os.path.join(debug_dir, f"{video_name}_frame50_debug.jpg")

                                cv2.imwrite(debug_path, combined_debug)
                                print(f"Residual 이미지 저장 완료 : {debug_path}")

                                saved_debug=True

                            x, y, w, h = map(int, pred_bbox) # Bounding Box가 영상 경계를 벗어나지 않도록 Clipping
                            x = max(0, x)
                            y = max(0, y)
                            w = min(w, min(w, w_img - x))
                            h = min(h, min(h, h_img - y)) # 따라서 유효한 ROI를 보장할 수 있음.

                            if w <= 0 or h <= 0:
                                track_active=False
                                gmc_initialized=False
                                pred_bbox = [0]
                            else:
                                inside = residual[y:y+h, x:x+w] # Residual과 BB의 교집합 행렬
                                inside_score = np.mean(inside)

                                outside_mask = np.ones_like(residual, dtype=np.uint8)
                                outside_mask[y:y+h, x:x+w] = 0 # BB안쪽 (inside)
                                outside_score = np.mean(residual[outside_mask == 1])

                                ratio = inside_score / (outside_score + 1e-6)

                            #if ratio < 1.1:
                            # 정상 추적 (ratio > 1)

                            # Hallucination (bbox가 배경 : ratio =1)
                                if ratio < 0.001:
                                    track_active = False
                                    gmc_initialized = False # 다음 프레임에서 GMC 다시 초기화 : 이전 motion 모델 신뢰하지 않음 -> Hallucination 발생하면 motion 모델도 신뢰 X
                                    pred_bbox = [0]

                    if len(good_new) > 0:
                        p0 = good_new.reshape(-1, 1, 2)

                if p0 is None or len(p0) < 20:
                    p0 = cv2.goodFeaturesToTrack(prev_gray, 80, 0.01, 7, blockSize=7)

            prev_gray = curr_gray.copy()

            if frame_id < len(gt_rects):
                if len(pred_bbox) > 1:
                    video_preds.append(pred_bbox)
                else:
                    video_preds.append([0])
            if len(pred_bbox) > 1:
                formatted_bbox = [int(v) for v in pred_bbox]
            else:
                formatted_bbox=[0]
            out_res.append(formatted_bbox)

            # Ensure frame_id is within bounds of gt_rects and exist_flags
            if frame_id < len(gt_rects) and exist_flags[frame_id] == 1:

                if len(pred_bbox) > 1:
                    iou_score = iou(pred_bbox, gt_rects[frame_id])
                else:
                    iou_score = 0.0

                video_ious.append(iou_score)

            # Visualization
            if visualization:
                if len(pred_bbox) > 1:
                    x, y, w, h = map(int, pred_bbox)
                    cv2.rectangle(im_vis, (x,y), (x+w, y+h), (0, 0, 255), 2)
                video_writer.write(im_vis)

        txt_file_path = os.path.join(submission_dir, f"{video_name}.txt")
        with open(txt_file_path, "w") as f:
            json.dump({"res" : out_res}, f)
        print(f"[{video_name}] .txt file successfully saved.")

        if visualization:
            video_writer.release()
            print(f"저장 완료 {out_video_path}")
            mac_video_path = os.path.join(local_output_dir, f"{video_name}_mac_ready.mp4")
            os.system(f"ffmpeg -y -hide_banner -loglevel error -i '{out_video_path}' -vcodec libx264 '{mac_video_path}'")
            print(f"저장 완료 : {mac_video_path}")


        if len(video_ious) > 0:
            video_aoa = eval_aoa(video_preds, label_res)
            overall_success.append(video_aoa)
            print(f"{video_name} AOA : {video_aoa:.4f}")

    if len(video_paths) > 0:
        zip_filename = "Model.zip"
        print(f"\n Creating Submission zip file.. ({zip_filename})")

        with zipfile.ZipFile(zip_filename, "w", zipfile.ZIP_DEFLATED) as zipf:
            for txt_file in os.listdir(submission_dir):
                if txt_file.endswith(".txt"):
                    file_path = os.path.join(submission_dir, txt_file)
                    zipf.write(file_path, arcname=txt_file)
    print(f"Progress being Completed. '{zip_filename}' file is now ready.")

    if len(overall_success) > 0:
        final_score = np.mean(overall_success)
        print("\n===============================")
        print(f"Overall Success: {final_score:.4f}")
        print("===============================")

# if __name__ == '__main__':
#     main(mode='IR', visualization=True)

# 전체 수행
#main(mode='IR', visualization=False)

# Target 수행
targets = [
    # 이전에 AOA 값 -0.2000 로 실패한 것들
        "03_2499_0962-2461",
        "46_1",
        "20190925_111757_1_3",
        "new9_train_newfix",
        "new12_train_newfix",
        "wg2022_ir_052_split_01"
        # 이 중에서도 안되는것 많음! -> Background 특성 상 UAV와 비슷함.
        # Frame Difference로 Hallucination 대비 역량 강화해야할 듯
]

main(mode='IR', visualization=True, target_folders=targets)